/// Flutter icons Aircon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Aircon
///      fonts:
///       - asset: fonts/Aircon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Aircon {
  Aircon._();

  static const _kFontFam = 'Aircon';
  static const _kFontPkg = null;

  static const IconData user = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData like = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData send = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData medicine = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData back = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tick = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cancel = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData snooze = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData steps = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData quiz = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData food = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData streak = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData blood_sugar = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData blood_pressure = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lesson = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData next = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData weight = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData attach = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData point = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData meal_plan = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData progress = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData breathing = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lessons = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData aerobics = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
